### ISSUE TITLE
Extract navigation logic to a Coordinator/Flow Controller/Wireframe pattern

### ISSUE THREAD

**Issue by MoridinBG** [GGLozanov/GitHubExplorer#1]
Currently view controllers present each other and "know" the way they are presented.
https://www.hackingwithswift.com/articles/71/how-to-use-the-coordinator-pattern-in-ios-apps
https://khanlou.com/2015/01/the-coordinator/

**Comment by GGLozanov** [comment]
Issue ought to be resolved unless I've insufficiently tested the app and/or the coordinator pattern has only worked on my end.
