### ISSUE TITLE
Access tokens must be invalidated on logout

### ISSUE THREAD

**Issue by GGLozanov** [GGLozanov/GitHubExplorer#5]
# **Bug Report**

Bug Name: Access tokens are not invalidated on logout
Area Path: Login View > User view > Login view > GitHub OAuth redirect
Severity: **HIGH**
Priority: **HIGH**
Assigned to: @GGLozanov @alexvidenov @MoridinBG 
Reported By: @GGLozanov 
Reported On: 06.07.2020
Reason: Defect
Environment: iPhone 11 Xcode Simulator.

# **Description**

**User logout** in the app is handled only partially - access tokens are deleted locally, but are not invalidated with Github

# **Steps to Reproduce**

1. Login with an unauthorised GitHub account to the app.
2. Logout.

# **Potential Fix**
The issue may be resolved by revoking the user's access token through a request to [Github's authorisation endpoints](https://developer.github.com/v3/oauth_authorizations/).

**Comment by MoridinBG** [comment]
You have denied Safari's request to open the app. Uninstall app, close Safari tabs & try again.
Invalidating issued tokens is a good suggestion.

**Comment by GGLozanov** [comment]
Oh right, it seems I haven't reconfigured my environment to simulate the proper behaviour. Apologies. 

Though yes, the point still stands that tokens should be invalidated upon logout to simulate a **true** logout and detachment from the OAuth2 app.

**Comment by alexvidenov** [comment]
This looks like the resource we should follow in order to revoke grant of specific user with their access token: https://docs.github.com/en/rest/reference/apps#delete-an-app-authorization
